import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),ORBITAL_SPEED=29.78,openedAt=performance.now();
let scene,camera,renderer,globe,earth,clouds,lights,moon,moonMesh,moonPhaseCanvas,moonPhaseCtx,moonPhaseTexture,moonPhasePlane,homeMarker,subsolarMarker,terminatorLine,sunObject,home=null,followMe=false,mouseX=0,mouseY=0,yaw=0,currentMoon=moonInfo();
const EARTH_RADIUS=1.61,MARKER_RADIUS=EARTH_RADIUS+.055,PRESENTATION_SPIN=.0005,loader=new THREE.TextureLoader();loader.crossOrigin='anonymous';
const notice=()=>{const el=$('notice');if(el)el.style.display='block'};
try{init();animate()}catch(e){console.error(e);notice()}
updateClock();updateMotion();refreshData();setInterval(updateClock,1000);setInterval(updateMotion,1000);setInterval(refreshData,600000);
function init(){const canvas=$('scene');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,100);camera.position.set(0,.22,7.42);renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;scene.add(new THREE.AmbientLight(0x142434,.74));const sol=new THREE.DirectionalLight(0xfff2cc,4.8);sol.position.set(-5,1.65,3.8);scene.add(sol);const rim=new THREE.DirectionalLight(0x6de8ff,1.28);rim.position.set(4.2,1.2,-2.4);scene.add(rim);globe=new THREE.Group();globe.position.set(0,-.2,0);scene.add(globe);earth=new THREE.Mesh(new THREE.SphereGeometry(EARTH_RADIUS,128,128),new THREE.MeshPhongMaterial({map:tex('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg'),shininess:14,specular:new THREE.Color(0x1b3458)}));globe.add(earth);lights=new THREE.Mesh(new THREE.SphereGeometry(EARTH_RADIUS+.004,128,128),new THREE.MeshBasicMaterial({map:tex('https://threejs.org/examples/textures/planets/earth_lights_2048.png'),transparent:true,opacity:.30,blending:THREE.AdditiveBlending,depthWrite:false}));globe.add(lights);clouds=new THREE.Mesh(new THREE.SphereGeometry(EARTH_RADIUS+.027,128,128),new THREE.MeshLambertMaterial({map:tex('https://threejs.org/examples/textures/planets/earth_clouds_1024.png'),transparent:true,opacity:.34,depthWrite:false}));globe.add(clouds);globe.add(new THREE.Mesh(new THREE.SphereGeometry(EARTH_RADIUS+.12,128,128),new THREE.MeshBasicMaterial({color:0x6de8ff,transparent:true,opacity:.12,side:THREE.BackSide,blending:THREE.AdditiveBlending})));homeMarker=marker(0x6de8ff,.026);homeMarker.visible=false;globe.add(homeMarker);subsolarMarker=marker(0xffd06f,.014);subsolarMarker.visible=false;globe.add(subsolarMarker);terminatorLine=makeTerminatorLine();globe.add(terminatorLine);moon=makeMoon();scene.add(moon);sunObject=makeSunVector();makeOrbitRings();$('subsolarLabel').style.display='none';addEventListener('resize',resize);document.addEventListener('mousemove',e=>{mouseX=e.clientX/innerWidth-.5;mouseY=e.clientY/innerHeight-.5});$('locBtn')?.addEventListener('click',requestHomePort);$('followBtn')?.addEventListener('click',toggleFollow);$('refreshBtn')?.addEventListener('click',refreshData);$('noticeClose')?.addEventListener('click',()=>{$('notice').style.display='none'})}
function tex(url){const t=loader.load(url,undefined,undefined,notice);t.colorSpace=THREE.SRGBColorSpace;return t}
function marker(color,size){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.SphereGeometry(size,24,24),new THREE.MeshBasicMaterial({color})));g.add(new THREE.Mesh(new THREE.TorusGeometry(size*2.4,size*.13,10,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.85})));return g}
function makeMoon(){const g=new THREE.Group();moonMesh=new THREE.Mesh(new THREE.SphereGeometry(.30,64,64),new THREE.MeshPhongMaterial({map:tex('https://threejs.org/examples/textures/planets/moon_1024.jpg'),shininess:2}));g.add(moonMesh);moonPhaseCanvas=document.createElement('canvas');moonPhaseCanvas.width=moonPhaseCanvas.height=192;moonPhaseCtx=moonPhaseCanvas.getContext('2d');moonPhaseTexture=new THREE.CanvasTexture(moonPhaseCanvas);moonPhasePlane=new THREE.Mesh(new THREE.PlaneGeometry(.62,.62),new THREE.MeshBasicMaterial({map:moonPhaseTexture,transparent:true,opacity:.88,depthWrite:false,side:THREE.DoubleSide}));moonPhasePlane.position.z=.305;g.add(moonPhasePlane);g.position.set(2.34,.92,-.08);return g}
function makeSunVector(){const g=new THREE.Group();g.position.set(-4.92,1.32,0);g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.04,0,0),new THREE.Vector3(2.68,-.84,0)]),new THREE.LineBasicMaterial({color:0xffd06f,transparent:true,opacity:.62})));g.add(new THREE.Mesh(new THREE.SphereGeometry(.105,32,32),new THREE.MeshBasicMaterial({color:0xffd06f})));scene.add(g);return g}
function makeOrbitRings(){const mat=new THREE.LineBasicMaterial({color:0x6de8ff,transparent:true,opacity:.045});for(const r of [2,2.42,2.86]){const pts=[];for(let i=0;i<=240;i++){const a=i/240*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r*.15-.2,-.18))}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),mat))}}
function makeTerminatorLine(){return new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x6de8ff,transparent:true,opacity:.26}))}
function latLonToVector3(lat,lon,r=MARKER_RADIUS){const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta))}
function setHomeMarker(){if(!home)return;homeMarker.position.copy(latLonToVector3(home.lat,home.lon));homeMarker.lookAt(new THREE.Vector3(0,0,0))}
function setSubsolarMarker(sun){subsolarMarker.position.copy(latLonToVector3(sun.subsolarLat,sun.subsolarLon,EARTH_RADIUS+.07));subsolarMarker.lookAt(new THREE.Vector3(0,0,0));subsolarMarker.visible=isObjectFront(subsolarMarker)}
function updateTerminatorLine(sun){const sv=latLonToVector3(sun.subsolarLat,sun.subsolarLon,1).normalize(),ref=Math.abs(sv.y)>.92?new THREE.Vector3(1,0,0):new THREE.Vector3(0,1,0),u=new THREE.Vector3().crossVectors(sv,ref).normalize(),v=new THREE.Vector3().crossVectors(sv,u).normalize(),r=EARTH_RADIUS+.045,pts=[];for(let i=0;i<256;i++){const a=i/256*Math.PI*2;pts.push(new THREE.Vector3().copy(u).multiplyScalar(Math.cos(a)*r).add(v.clone().multiplyScalar(Math.sin(a)*r)))}terminatorLine.geometry.setFromPoints(pts)}
function isObjectFront(obj){const w=new THREE.Vector3();obj.getWorldPosition(w);const n=w.clone().sub(globe.position).normalize();return n.dot(camera.position.clone().sub(w).normalize())>-.08}
function labelObject(obj,label,dx=38,dy=-10,requireFront=true){if(!label)return;const w=new THREE.Vector3();obj.getWorldPosition(w);const ok=!requireFront||isObjectFront(obj);w.project(camera);const x=(w.x*.5+.5)*innerWidth,y=(-w.y*.5+.5)*innerHeight,on=ok&&w.z<1&&x>0&&x<innerWidth&&y>0&&y<innerHeight;label.style.left=`${x+dx}px`;label.style.top=`${y+dy}px`;label.style.display=on?'block':'none'}
function updateMoonPhaseOverlay(){if(!moonPhaseCtx)return;const c=96,r=92,illum=currentMoon.illumination/100,w=Math.max(1,2*r*illum),wax=currentMoon.phase<.5;moonPhaseCtx.clearRect(0,0,192,192);moonPhaseCtx.save();moonPhaseCtx.beginPath();moonPhaseCtx.arc(c,c,r,0,Math.PI*2);moonPhaseCtx.clip();moonPhaseCtx.fillStyle='rgba(0,0,0,.78)';moonPhaseCtx.fillRect(0,0,192,192);if(illum>.985){moonPhaseCtx.clearRect(0,0,192,192)}else if(illum>.015){moonPhaseCtx.globalCompositeOperation='destination-out';moonPhaseCtx.fillStyle='rgba(0,0,0,1)';moonPhaseCtx.beginPath();const cx=wax?c+r-w/2:c-r+w/2;moonPhaseCtx.ellipse(cx,c,w/2,r,0,0,Math.PI*2);moonPhaseCtx.fill()}moonPhaseCtx.restore();moonPhaseTexture.needsUpdate=true}
function animate(){requestAnimationFrame(animate);const now=new Date(),sun=solarGeometry(now);currentMoon=moonInfo(now);if(followMe&&home){const target=THREE.MathUtils.degToRad(-home.lon-90);yaw+=shortestAngle(target-yaw)*.025}else yaw+=PRESENTATION_SPIN;globe.rotation.y=yaw;clouds.rotation.y+=.00035;setSubsolarMarker(sun);updateTerminatorLine(sun);const a=currentMoon.phase*Math.PI*2;moon.position.set(2.34+Math.cos(a)*.20,.92+Math.sin(a)*.32,-.08+Math.sin(a)*.16);moon.lookAt(globe.position);updateMoonPhaseOverlay();camera.position.x+=(mouseX*.15-camera.position.x)*.03;camera.position.y+=(.22-mouseY*.09-camera.position.y)*.03;camera.lookAt(0,-.08,0);if(home){setHomeMarker();homeMarker.visible=true;$('daylightState').textContent=isDayAt(home.lat,home.lon,sun)?'Day side':'Night side';labelObject(homeMarker,$('homeLabel'),38,-10,true)}else $('homeLabel').style.display='none';labelObject(sunObject,$('sunLabel'),40,-8,false);$('subsolarLabel').style.display='none';$('subsolarLat').textContent=`${sun.subsolarLat.toFixed(2)}°`;$('subsolarLon').textContent=`${sun.subsolarLon.toFixed(2)}°`;$('declination').textContent=`${sun.declination.toFixed(2)}°`;if($('moonIllumination'))$('moonIllumination').textContent=`${currentMoon.illumination}%`;renderer.render(scene,camera)}
function shortestAngle(a){return Math.atan2(Math.sin(a),Math.cos(a))}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function updateClock(){const n=new Date();$('time').textContent=`${pad(n.getUTCHours())}:${pad(n.getUTCMinutes())}:${pad(n.getUTCSeconds())} UTC`;$('date').textContent=n.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'short',day:'numeric'});if(home)$('localTime').textContent=n.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}
function formatKm(km){return km>1e6?`${(km/1e6).toFixed(2)}M km`:`${Math.round(km).toLocaleString()} km`}
function updateMotion(){const n=new Date(),elapsed=(performance.now()-openedAt)/1000,today=n.getUTCHours()*3600+n.getUTCMinutes()*60+n.getUTCSeconds();if($('distanceOpen'))$('distanceOpen').textContent=formatKm(elapsed*ORBITAL_SPEED);if($('distanceToday'))$('distanceToday').textContent=formatKm(today*ORBITAL_SPEED)}
function moonInfo(date=new Date()){const period=2551443,synodic=29.530588853,base=new Date(Date.UTC(2001,0,24,13,35,0)).getTime()/1000,phase=(((date.getTime()/1000-base)%period)+period)%period/period,age=phase*synodic,illumination=Math.round((1-Math.cos(phase*Math.PI*2))/2*100);let name='New';if(age<1.84566)name='New';else if(age<5.53699)name='Waxing crescent';else if(age<9.22831)name='First quarter';else if(age<12.91963)name='Waxing gibbous';else if(age<16.61096)name='Full';else if(age<20.30228)name='Waning gibbous';else if(age<23.99361)name='Last quarter';else if(age<27.68493)name='Waning crescent';return{name,age:age.toFixed(1),phase,illumination}}
function solarGeometry(date=new Date()){const start=new Date(Date.UTC(date.getUTCFullYear(),0,0)),day=Math.floor((date-start)/86400000),hour=date.getUTCHours()+date.getUTCMinutes()/60+date.getUTCSeconds()/3600,g=2*Math.PI/365*(day-1+(hour-12)/24),decl=.006918-.399912*Math.cos(g)+.070257*Math.sin(g)-.006758*Math.cos(2*g)+.000907*Math.sin(2*g)-.002697*Math.cos(3*g)+.00148*Math.sin(3*g),eq=229.18*(.000075+.001868*Math.cos(g)-.032077*Math.sin(g)-.014615*Math.cos(2*g)-.040849*Math.sin(2*g)),m=date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60;let lon=180-(m+eq)/4;lon=((lon+540)%360)-180;return{declination:decl*180/Math.PI,subsolarLat:decl*180/Math.PI,subsolarLon:lon}}
function isDayAt(lat,lon,sun){const la=lat*Math.PI/180,sl=sun.subsolarLat*Math.PI/180,ld=(lon-sun.subsolarLon)*Math.PI/180;return Math.sin(la)*Math.sin(sl)+Math.cos(la)*Math.cos(sl)*Math.cos(ld)>0}
function requestHomePort(){if(!navigator.geolocation){$('homeStatus').textContent='No geolocation API';$('homePosition').textContent='Unavailable';return}$('homeStatus').textContent='Requesting location';navigator.geolocation.getCurrentPosition(pos=>{home={lat:pos.coords.latitude,lon:pos.coords.longitude};$('homeStatus').textContent='Home port locked';$('homePosition').textContent=`${home.lat.toFixed(3)}°, ${home.lon.toFixed(3)}°`;$('localTime').textContent=new Date().toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});followMe=true;$('followBtn').textContent='Follow me: on';$('followBtn').classList.add('toggle-on');setHomeMarker();refreshData()},()=>{$('homeStatus').textContent='Location denied';$('homePosition').textContent='Manual mode'},{enableHighAccuracy:false,timeout:8000,maximumAge:600000})}
function toggleFollow(){followMe=!followMe;$('followBtn').textContent=`Follow me: ${followMe?'on':'off'}`;$('followBtn').classList.toggle('toggle-on',followMe)}
async function fetchQuakes(){try{const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.geojson'),d=await r.json(),events=d.features||[];$('quakeCount').textContent=events.length;return{count:events.length}}catch{$('quakeCount').textContent='offline';return{count:'unknown'}}}
async function fetchISS(){try{const r=await fetch('https://api.wheretheiss.at/v1/satellites/25544'),d=await r.json();$('iss').textContent=`${d.latitude.toFixed(2)}°, ${d.longitude.toFixed(2)}°`}catch{$('iss').textContent='offline'}}
async function fetchSolarWind(){try{const r=await fetch('https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json'),rows=await r.json(),last=rows.slice(1).reverse().find(row=>row[2]);$('solarWind').textContent=last?`${Number(last[2]).toFixed(0)} km/s`:'quiet'}catch{$('solarWind').textContent='offline'}}
async function refreshData(){currentMoon=moonInfo();$('moonPhase').textContent=currentMoon.name;$('moonAge').textContent=`${currentMoon.age} days`;if($('moonIllumination'))$('moonIllumination').textContent=`${currentMoon.illumination}%`;const quake=await fetchQuakes();await Promise.all([fetchISS(),fetchSolarWind()]);const hp=home?` Home port is locked at ${home.lat.toFixed(2)}°, ${home.lon.toFixed(2)}° and currently on the ${$('daylightState').textContent.toLowerCase()}.`:' Home port is standing by pending location permission.';$('shipLog').textContent=`Earth remains in stable transit around Sol at approximately 29.78 km/s. Lunar telemetry reports a ${currentMoon.name.toLowerCase()} phase, ${currentMoon.age} days into cycle, ${currentMoon.illumination}% illuminated. Seismic feed shows ${quake.count} M4.5+ crust events in the prior 24 hours.${hp}`}
